// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(Da1quanLyCuaHangContext))]
    [Migration("20240804153844_UpdateNhanVien")]
    partial class UpdateNhanVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.DoanhThu", b =>
                {
                    b.Property<int>("DoanhThuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DoanhThuID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoanhThuId"));

                    b.Property<Guid?>("HoaDonId")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HoaDonID");

                    b.Property<DateOnly?>("Ngay")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongDoanhThu")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("DoanhThuId")
                        .HasName("PK__DoanhThu__D2C18FB110B2BE0D");

                    b.HasIndex("HoaDonId");

                    b.ToTable("DoanhThu", (string)null);
                });

            modelBuilder.Entity("DAL.Models.GiamGium", b =>
                {
                    b.Property<string>("GiamGiaId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GiamGiaID");

                    b.Property<string>("MaGiamGia")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<decimal?>("PhanTramGiam")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("TienMax")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TienMin")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("GiamGiaId")
                        .HasName("PK__GiamGia__40AD8FA711F40A98");

                    b.ToTable("GiamGia");
                });

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.Property<Guid>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HoaDonID");

                    b.Property<string>("GiamGiaId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GiamGiaID");

                    b.Property<string>("HinhThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KhachHangId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KhachHangID");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NhanVienID");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("HoaDonId")
                        .HasName("PK__HoaDon__6956CE69E93AA7D5");

                    b.HasIndex("GiamGiaId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("DAL.Models.HoaDonChiTiet", b =>
                {
                    b.Property<int>("HoaDonChiTietID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("HoaDonChiTietID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonChiTietID"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<Guid?>("HoaDonID")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HoaDonID");

                    b.Property<string>("SanPhamID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SanPhamID");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("HoaDonChiTietID")
                        .HasName("PK__HoaDonCh__603A404A7EC4FAC0");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("SanPhamID");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("DAL.Models.KhachHang", b =>
                {
                    b.Property<string>("KhachHangId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KhachHangID");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("KhachHangId")
                        .HasName("PK__KhachHan__880F211B2C151D95");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("DAL.Models.LoaiSanPham", b =>
                {
                    b.Property<string>("LoaiSanPhamId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiSanPhamID");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("LoaiSanPhamId")
                        .HasName("PK__LoaiSanP__AFC7DC85DA5791AA");

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("DAL.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaNhaCungCap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaNhaCungCap")
                        .HasName("PK__NhaCungC__53DA92056D3B48EC");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.Property<string>("NhanVienId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NhanVienID");

                    b.Property<byte?>("ChucVu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("tinyint");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("NhanVienId")
                        .HasName("PK__NhanVien__E27FD7EAC2C53589");

                    b.HasIndex(new[] { "Username" }, "UQ__NhanVien__536C85E4E5DD5949")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("DAL.Models.SanPham", b =>
                {
                    b.Property<string>("SanPhamId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SanPhamID");

                    b.Property<string>("Anh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("LoaiSanPhamId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiSanPhamID");

                    b.Property<string>("MaNhaCungCap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("NgayCapNhat")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("SanPhamId")
                        .HasName("PK__SanPham__05180FF475534720");

                    b.HasIndex("LoaiSanPhamId");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("DAL.Models.DoanhThu", b =>
                {
                    b.HasOne("DAL.Models.HoaDon", "HoaDon")
                        .WithMany("DoanhThus")
                        .HasForeignKey("HoaDonId")
                        .HasConstraintName("FK__DoanhThu__HoaDon__4D94879B");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.HasOne("DAL.Models.GiamGium", "GiamGia")
                        .WithMany("HoaDons")
                        .HasForeignKey("GiamGiaId")
                        .HasConstraintName("FK__HoaDon__GiamGiaI__46E78A0C");

                    b.HasOne("DAL.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangId")
                        .HasConstraintName("FK__HoaDon__KhachHan__44FF419A");

                    b.HasOne("DAL.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("NhanVienId")
                        .HasConstraintName("FK__HoaDon__NhanVien__45F365D3");

                    b.Navigation("GiamGia");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("DAL.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("HoaDonID")
                        .HasConstraintName("FK__HoaDonChi__HoaDo__49C3F6B7");

                    b.HasOne("DAL.Models.SanPham", "SanPham")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("SanPhamID")
                        .HasConstraintName("FK__HoaDonChi__SanPh__4AB81AF0");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DAL.Models.SanPham", b =>
                {
                    b.HasOne("DAL.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("LoaiSanPhamId")
                        .HasConstraintName("FK__SanPham__LoaiSan__3F466844");

                    b.HasOne("DAL.Models.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNhaCungCap")
                        .HasConstraintName("FK__SanPham__MaNhaCu__403A8C7D");

                    b.Navigation("LoaiSanPham");

                    b.Navigation("MaNhaCungCapNavigation");
                });

            modelBuilder.Entity("DAL.Models.GiamGium", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.Navigation("DoanhThus");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("DAL.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DAL.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DAL.Models.NhaCungCap", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DAL.Models.SanPham", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
